name: Student Registration Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run HTML tests
        run: |
          chmod +x test.sh
          ./test.sh
